baseURL: "https://examplesite.com"
title: ExampleSite
paginate: 5
theme: hugo-PaperMod
publishDir: docs

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  author: Me
  # author: ["Me", "You"] # multiple authors

  images: "<link or path of image for opengraph, twitter-cards>"

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: light
  disableThemeToggle: true
  disableSpecial1stPost: false

  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "images/mihrap512.png"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: ""
    icon: /images/mihrap512.png
    iconHeight: 150

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
      
      
menu:
  main:
    - identifier: about
      name: about hugo
      pre: <i class='fa fa-heart'></i>
      url: /about/
      weight: -110
      
    - name: sayi 1
      url: /getting-started/
      parent: about

    - name: sayi 2
      url: /getting-started/
      parent: about  
       

    - name: getting started
      post: <span class='alert'>New!</span>
      pre: <i class='fa fa-road'></i>
      url: /getting-started/
      weight: -100      