baseURL: "https://mihrapdergisi.com"
title: Mihrap Dergisi
paginate: 5
theme: hugo-PaperMod
publishDir: docs
googleAnalytics: UA-130362437-4
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
canonifyurls: false
minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Mihrap Dergisi
  description: "Mihrap Dergisi"
  author: Mihrap
  # author: ["Me", "You"] # multiple authors

  images: "<link or path of image for opengraph, twitter-cards>"

  ShowReadingTime: true
  ShowShareButtons: false
  comments: false
  defaultTheme: light
  disableThemeToggle: true
  disableSpecial1stPost: false

  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "images/mihrap512.png"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: ""
    icon: /images/mihrap512.png
    iconHeight: 150

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Mihrap Dergisi
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Mihrap Dergisi

  socialIcons:
    - name: facebook
      url: "https://www.facebook.com/mihrapdergi"
    - name: twitter
      url: "https://twitter.com/mihrapdergisi"
    - name: instagram
      url: "https://www.instagram.com/mihrapdergisi/"
    - name: youtube
      url: "https://www.youtube.com/channel/UC__FOJUfaZXLTHF_Tl3XZ9A"



  analytics:
    google:
      SiteVerificationTag: "XYZabc"
      
      
menu:
  main:
    - identifier: sayi
      name: Sayılarımız
      weight: 1
      
   
    - name: 1. Sayı
      url: http://bit.ly/2VOC3QJ
      parent: sayi
      weight: 1
      
    - name: 2. Sayı
      url: http://bit.ly/32Us3ah
      parent: sayi
      weight: 2

      
    - name: 3. Sayı
      url: http://bit.ly/2xhLE8D
      parent: sayi  
      weight: 3

      
    - name: 4. Sayı
      url: https://bit.ly/2XEw5T4
      parent: sayi
      weight: 4

      
    - name: 5. Sayı
      url: https://bit.ly/356m70Y
      parent: sayi
      weight: 5


    - name: 6. Sayı
      url: https://bit.ly/3mHwazD
      parent: sayi
      weight: 6

      
    - name: 7. Sayı
      url: http://bit.ly/3c0GjDp
      parent: sayi  
      weight: 7


    - name: 8. Sayı
      url: https://bit.ly/3vRFk0S
      parent: sayi   
      weight: 8


    - name: 9. Sayı
      url: https://bit.ly/3yFgnGA
      parent: sayi   
      weight: 9

    - name: 10. Sayı
      url: https://bit.ly/332NXfF
      parent: sayi    
      weight: 10

    - name: 11. Sayı
      url: https://bit.ly/3hEXVYv
      parent: sayi    
      weight: 11

    - name: 12. Sayı
      url: https://bit.ly/3Q1xo7W
      parent: sayi    
      weight: 12
       


    - name: İletişim
      url: /iletisim/
      weight: 2


    - name: mihrap.org
      url: https://mihrap.org
     